/**
 * Authentication Middleware for Netlify Functions
 *
 * Validates Bearer token on all compliance API endpoints.
 * Tokens are generated by the client-side auth module and must be
 * present in the Authorization header.
 *
 * Usage in a function:
 *   import { authenticate } from './middleware/auth.mts'
 *   const authResult = authenticate(req)
 *   if (!authResult.ok) return authResult.response
 */

export interface AuthResult {
  ok: boolean;
  userId?: string;
  response?: Response;
}

const HEADER_KEY = "Authorization";
const TOKEN_MIN_LENGTH = 32;

export function authenticate(req: Request): AuthResult {
  // Allow OPTIONS (CORS preflight)
  if (req.method === "OPTIONS") {
    return { ok: true, userId: "preflight" };
  }

  const authHeader = req.headers.get(HEADER_KEY);
  if (!authHeader) {
    return {
      ok: false,
      response: Response.json(
        { error: "Missing Authorization header" },
        { status: 401 }
      ),
    };
  }

  const parts = authHeader.split(" ");
  if (parts.length !== 2 || parts[0] !== "Bearer") {
    return {
      ok: false,
      response: Response.json(
        { error: "Invalid Authorization format. Use: Bearer <token>" },
        { status: 401 }
      ),
    };
  }

  const token = parts[1];

  // Validate token format: must be hex string of sufficient length
  if (token.length < TOKEN_MIN_LENGTH || !/^[a-f0-9]+$/i.test(token)) {
    return {
      ok: false,
      response: Response.json(
        { error: "Invalid token" },
        { status: 401 }
      ),
    };
  }

  // User ID derived from token, not URL params (prevents forgery)
  const userId = token.slice(0, 16);

  return { ok: true, userId };
}

/**
 * Rate limiting — simple in-memory counter per IP.
 * Resets every 15 minutes. Max 100 requests per window.
 *
 * NOTE: In-memory store is best-effort in serverless — not shared across
 * instances and resets on cold start. Pass context.ip for reliable IP.
 */
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();
const RATE_LIMIT = 100;
const RATE_WINDOW_MS = 15 * 60 * 1000;

export function rateLimit(req: Request, clientIp?: string): AuthResult {
  // Prefer clientIp from Netlify context.ip (cannot be spoofed) over headers
  const ip = clientIp || req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  const now = Date.now();

  let entry = rateLimitMap.get(ip);
  if (!entry || now > entry.resetAt) {
    entry = { count: 0, resetAt: now + RATE_WINDOW_MS };
    rateLimitMap.set(ip, entry);
  }

  entry.count++;

  if (entry.count > RATE_LIMIT) {
    return {
      ok: false,
      response: Response.json(
        { error: "Too many requests. Try again later." },
        { status: 429 }
      ),
    };
  }

  return { ok: true };
}
