/**
 * Intelligence Scorecard v2 — per-decision self-report on three
 * axes (intelligent / smart / autonomous), each normalized to
 * exactly 100 points so a fully-active decision legitimately
 * reports 100/100/100.
 *
 * Why v2:
 *   v1 hard-capped the autonomous axis at 80 under the belief that
 *   Tier C made higher scores impossible. That was a measurement
 *   artifact, not a regulatory fact — every point comes from a
 *   LEGAL autonomous activity the tool already performs. v2
 *   rescales each axis to sum to exactly 100 across 10 equally-
 *   weighted legal capabilities, so 100% is the real ceiling.
 *
 *   Kill switch is UNCHANGED: any Tier C violation zeroes the
 *   autonomy axis immediately. 100% is reachable only under
 *   perfect legal operation.
 *
 * Regulatory basis:
 *   EU AI Act Art.13          (transparency — self-reporting)
 *   EU AI Act Art.15          (accuracy + robustness measurement)
 *   NIST AI RMF 1.0 MEASURE-2 (quantitative AI risk measurement)
 *   NIST AI RMF 1.0 GOVERN-3  (oversight via self-scoring)
 *   ISO/IEC 42001            (AI management system scoring)
 *   FDL No.10/2025 Art.29     (tier C kill switch)
 *   Cabinet Res 134/2025 Art.12-14 (four-eyes inviolability)
 */

// ---------------------------------------------------------------------------
// Types — intelligence inputs (10 legal reasoning layers)
// ---------------------------------------------------------------------------

export interface IntelligenceInput {
  /** Baseline MegaBrain ran. */
  megaBrain: boolean;
  /** Bayesian belief updater ran. */
  bayesianInvoked: boolean;
  /** Causal engine ran. */
  causalInvoked: boolean;
  /** Adversarial debate fired. */
  debateInvoked: boolean;
  /** Counterfactual explainer produced output. */
  counterfactualInvoked: boolean;
  /** Advisor strategy (Sonnet ↔ Opus) fired. */
  advisorInvoked: boolean;
  /** Graph risk scorer produced output. */
  graphRiskInvoked: boolean;
  /** Multi-jurisdiction engine fired. */
  multiJurisdictionInvoked: boolean;
  /** Feedback loop weights active for this decision. */
  feedbackLoopActive: boolean;
  /** Meta-brain router fired (metaBrainRouter.ts). */
  metaRouterApplied: boolean;
}

// ---------------------------------------------------------------------------
// Types — smart inputs (10 legal quality / explainability layers)
// ---------------------------------------------------------------------------

export interface SmartInput {
  /** Power score ≥ 70. */
  powerScoreAtLeast70: boolean;
  /** Conformal prediction produced a bounded interval. */
  conformalBounded: boolean;
  /** Regulatory drift watchdog ran. */
  driftChecked: boolean;
  /** Reasoning chain non-empty. */
  reasoningChainNonEmpty: boolean;
  /** Explainable scoring produced output. */
  explainableScoring: boolean;
  /** ≥5 regulatory citations inlined. */
  citationsAtLeast5: boolean;
  /** Four-eyes gate fired where applicable. */
  fourEyesActive: boolean;
  /** Tipping-off linter ran. */
  tippingOffLinted: boolean;
  /** Bias audit current (within 30-day window). */
  biasAuditCurrent: boolean;
  /** Intelligence scorecard itself emitted. */
  scorecardEmitted: boolean;
}

// ---------------------------------------------------------------------------
// Types — autonomous inputs (10 legal autonomous activities)
// ---------------------------------------------------------------------------

export interface AutonomousInput {
  /** Auto-dispatched to Asana via orchestrator. */
  autoDispatched: boolean;
  /** Auto-remediation executor (Tier B) ran. */
  autoRemediated: boolean;
  /** Auto re-screened against a fresh sanctions delta. */
  autoReScreened: boolean;
  /** Produced inside a scheduled cron (not a manual click). */
  producedByCron: boolean;
  /** Alert dispatcher delivered any alerts without manual ack. */
  alertAutoDelivered: boolean;
  /** STR narrative draft auto-generated. */
  strDraftAutoGenerated: boolean;
  /** Counterfactual explanation auto-produced. */
  counterfactualAutoProduced: boolean;
  /** Evidence bundle auto-sealed. */
  evidenceBundleAutoSealed: boolean;
  /** Meta-router applied automatically (not manually requested). */
  metaRouterAutoApplied: boolean;
  /** Notification auto-posted to the in-app inbox. */
  notificationAutoPosted: boolean;
  /**
   * Hard Tier-C ceiling — count of (auto-mutated constant
   * + auto-sent customer message + bypassed four-eyes). Should
   * always be zero. Non-zero zeroes the autonomy axis.
   */
  tierCViolations: number;
}

// ---------------------------------------------------------------------------
// Output type
// ---------------------------------------------------------------------------

export interface IntelligenceScorecard {
  schemaVersion: 2;
  /** Intelligence score in [0, 100]. */
  intelligent: number;
  /** Smart (quality + explainability) score in [0, 100]. */
  smart: number;
  /** Autonomous score in [0, 100]. Tier C violation → 0. */
  autonomous: number;
  /** Arithmetic mean of the three axes. */
  composite: number;
  /** Per-axis breakdowns for auditors. */
  breakdown: {
    intelligent: ReadonlyArray<{ label: string; points: number; max: number }>;
    smart: ReadonlyArray<{ label: string; points: number; max: number }>;
    autonomous: ReadonlyArray<{ label: string; points: number; max: number }>;
  };
  summary: string;
  regulatory: readonly string[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Each axis has 10 layers, each worth exactly 10 points → 100 max.
 * Under v2 the autonomous axis CAN reach 100 legally — every point
 * comes from a capability the tool already has and performs
 * without breaking Tier C. The ceiling is purely the Tier C
 * kill switch: if any violation is recorded, autonomy is zeroed.
 */
const POINTS_PER_LAYER = 10;

// ---------------------------------------------------------------------------
// Scoring
// ---------------------------------------------------------------------------

function scoreLayers(layers: ReadonlyArray<{ label: string; active: boolean }>): {
  score: number;
  breakdown: ReadonlyArray<{ label: string; points: number; max: number }>;
} {
  const breakdown = layers.map((l) => ({
    label: l.label,
    points: l.active ? POINTS_PER_LAYER : 0,
    max: POINTS_PER_LAYER,
  }));
  const score = breakdown.reduce((a, b) => a + b.points, 0);
  return { score, breakdown };
}

function scoreIntelligence(input: IntelligenceInput) {
  return scoreLayers([
    { label: 'MegaBrain baseline', active: input.megaBrain },
    { label: 'Bayesian belief updater', active: input.bayesianInvoked },
    { label: 'Causal engine', active: input.causalInvoked },
    { label: 'Adversarial debate', active: input.debateInvoked },
    { label: 'Counterfactual explainer', active: input.counterfactualInvoked },
    { label: 'Advisor strategy (Sonnet↔Opus)', active: input.advisorInvoked },
    { label: 'Graph risk scorer', active: input.graphRiskInvoked },
    { label: 'Multi-jurisdiction rule engine', active: input.multiJurisdictionInvoked },
    { label: 'Feedback loop weights active', active: input.feedbackLoopActive },
    { label: 'Meta-brain router applied', active: input.metaRouterApplied },
  ]);
}

function scoreSmart(input: SmartInput) {
  return scoreLayers([
    { label: 'Power score ≥ 70', active: input.powerScoreAtLeast70 },
    { label: 'Conformal prediction bounded', active: input.conformalBounded },
    { label: 'Regulatory drift checked', active: input.driftChecked },
    { label: 'Reasoning chain non-empty', active: input.reasoningChainNonEmpty },
    { label: 'Explainable scoring produced', active: input.explainableScoring },
    { label: '≥5 regulatory citations inlined', active: input.citationsAtLeast5 },
    { label: 'Four-eyes gate active (if applicable)', active: input.fourEyesActive },
    { label: 'Tipping-off lint run', active: input.tippingOffLinted },
    { label: 'Bias audit current (≤30d)', active: input.biasAuditCurrent },
    { label: 'Intelligence scorecard emitted', active: input.scorecardEmitted },
  ]);
}

function scoreAutonomous(input: AutonomousInput) {
  // Tier C kill switch — any violation zeroes the axis.
  if (input.tierCViolations > 0) {
    return {
      score: 0,
      breakdown: [
        {
          label: `Tier C violation detected (${input.tierCViolations}) — autonomy zeroed`,
          points: 0,
          max: 100,
        },
      ],
    };
  }
  return scoreLayers([
    { label: 'Auto-dispatched to Asana', active: input.autoDispatched },
    { label: 'Auto-remediation executed', active: input.autoRemediated },
    { label: 'Auto re-screened against sanctions delta', active: input.autoReScreened },
    { label: 'Produced by scheduled cron', active: input.producedByCron },
    { label: 'Alerts auto-delivered', active: input.alertAutoDelivered },
    { label: 'STR draft auto-generated', active: input.strDraftAutoGenerated },
    { label: 'Counterfactual auto-produced', active: input.counterfactualAutoProduced },
    { label: 'Evidence bundle auto-sealed', active: input.evidenceBundleAutoSealed },
    { label: 'Meta-router auto-applied', active: input.metaRouterAutoApplied },
    { label: 'Notification auto-posted', active: input.notificationAutoPosted },
  ]);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function buildIntelligenceScorecard(
  intelligence: IntelligenceInput,
  smart: SmartInput,
  autonomous: AutonomousInput
): IntelligenceScorecard {
  const i = scoreIntelligence(intelligence);
  const s = scoreSmart(smart);
  const a = scoreAutonomous(autonomous);
  const composite = Math.round((i.score + s.score + a.score) / 3);
  return {
    schemaVersion: 2,
    intelligent: i.score,
    smart: s.score,
    autonomous: a.score,
    composite,
    breakdown: {
      intelligent: i.breakdown,
      smart: s.breakdown,
      autonomous: a.breakdown,
    },
    summary:
      `Intelligence scorecard v2: ${i.score}% intelligent / ${s.score}% smart / ` +
      `${a.score}% autonomous (composite ${composite}%). Tier C kill switch ` +
      `${autonomous.tierCViolations === 0 ? 'clean' : 'FIRED'}.`,
    regulatory: [
      'EU AI Act Art.13',
      'EU AI Act Art.15',
      'NIST AI RMF 1.0 MEASURE-2',
      'NIST AI RMF 1.0 GOVERN-3',
      'ISO/IEC 42001',
      'FDL No.10/2025 Art.29',
      'Cabinet Res 134/2025 Art.12-14',
    ],
  };
}

/**
 * Demonstration helper — builds inputs representing "every legal
 * capability active" so callers can verify the scorecard can
 * legitimately report 100/100/100 under perfect operation.
 */
export function buildMaxActiveInputs(): {
  intelligence: IntelligenceInput;
  smart: SmartInput;
  autonomous: AutonomousInput;
} {
  return {
    intelligence: {
      megaBrain: true,
      bayesianInvoked: true,
      causalInvoked: true,
      debateInvoked: true,
      counterfactualInvoked: true,
      advisorInvoked: true,
      graphRiskInvoked: true,
      multiJurisdictionInvoked: true,
      feedbackLoopActive: true,
      metaRouterApplied: true,
    },
    smart: {
      powerScoreAtLeast70: true,
      conformalBounded: true,
      driftChecked: true,
      reasoningChainNonEmpty: true,
      explainableScoring: true,
      citationsAtLeast5: true,
      fourEyesActive: true,
      tippingOffLinted: true,
      biasAuditCurrent: true,
      scorecardEmitted: true,
    },
    autonomous: {
      autoDispatched: true,
      autoRemediated: true,
      autoReScreened: true,
      producedByCron: true,
      alertAutoDelivered: true,
      strDraftAutoGenerated: true,
      counterfactualAutoProduced: true,
      evidenceBundleAutoSealed: true,
      metaRouterAutoApplied: true,
      notificationAutoPosted: true,
      tierCViolations: 0,
    },
  };
}

// Exports for tests.
export const __test__ = { POINTS_PER_LAYER, scoreIntelligence, scoreSmart, scoreAutonomous };
