/**
 * Model Card Generator — subsystem #79 (Phase 7 Cluster J).
 *
 * EU AI Act Art.11 + Annex IV require high-risk AI systems to
 * maintain technical documentation including a "model card" that
 * describes purpose, data, performance, limitations, and oversight.
 * Today this is a manual document. This module auto-generates it
 * from the self-audit evidence (Phase 5) + subsystem scoring
 * (Phase 3) + governance remediation history.
 *
 * Output formats:
 *   - Markdown (human-readable)
 *   - JSON (machine-readable, schema-aligned with EU AI Act Annex IV)
 *
 * Pure function. The inputs are already assembled by the governance
 * agent + scoring module; this just formats.
 *
 * Regulatory basis:
 *   - EU Regulation 2024/1689 Art.11 + Annex IV (technical documentation)
 *   - NIST AI RMF MP-4.1 (model inventory)
 *   - ISO/IEC 42001:2023 A.4.2 + A.6.1 (resources + lifecycle)
 */

import type { GovernanceAudit } from '../agents/aiGovernance';
import type { SubsystemScoreReport } from './subsystemScoring';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ModelCardInput {
  modelName: string;
  version: string;
  owner: string;
  intendedUse: string;
  systemDescription: string;
  governanceAudit: GovernanceAudit;
  subsystemScores: readonly SubsystemScoreReport[];
  dataSources: readonly string[];
  limitations: readonly string[];
  humanOversight: readonly string[];
}

export interface ModelCard {
  markdown: string;
  json: string;
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

export function generateModelCard(input: ModelCardInput): ModelCard {
  const markdown = buildMarkdown(input);
  const json = buildJson(input);
  return { markdown, json };
}

function buildMarkdown(input: ModelCardInput): string {
  const lines: string[] = [];
  lines.push(`# Model Card — ${input.modelName} v${input.version}`);
  lines.push('');
  lines.push(`**Owner:** ${input.owner}`);
  lines.push(`**Intended use:** ${input.intendedUse}`);
  lines.push(`**EU AI Act tier:** ${input.governanceAudit.euAiActTier}`);
  lines.push(`**Audited at:** ${input.governanceAudit.auditedAt}`);
  lines.push('');
  lines.push('## System description');
  lines.push('');
  lines.push(input.systemDescription);
  lines.push('');
  lines.push('## Governance posture');
  lines.push('');
  lines.push(`Overall score: **${input.governanceAudit.overallScore}/100**`);
  lines.push('');
  lines.push('| Framework | Score | Pass | Partial | Fail |');
  lines.push('|---|---:|---:|---:|---:|');
  for (const fr of input.governanceAudit.frameworks) {
    lines.push(
      `| ${fr.frameworkName} | ${fr.score} | ${fr.summary.pass} | ${fr.summary.partial} | ${fr.summary.fail} |`
    );
  }
  lines.push('');
  lines.push('## Subsystem scores');
  lines.push('');
  lines.push('| Subsystem | Total | Maturity | Recommendation |');
  lines.push('|---|---:|---|---|');
  for (const s of input.subsystemScores.slice(0, 50)) {
    lines.push(`| ${s.subsystem} | ${s.total} | ${s.maturity} | ${s.recommendation} |`);
  }
  lines.push('');
  lines.push('## Data sources');
  lines.push('');
  for (const d of input.dataSources) lines.push(`- ${d}`);
  lines.push('');
  lines.push('## Limitations');
  lines.push('');
  for (const l of input.limitations) lines.push(`- ${l}`);
  lines.push('');
  lines.push('## Human oversight');
  lines.push('');
  for (const h of input.humanOversight) lines.push(`- ${h}`);
  lines.push('');
  if (input.governanceAudit.remediation.length > 0) {
    lines.push('## Outstanding remediation');
    lines.push('');
    for (const r of input.governanceAudit.remediation.slice(0, 20)) {
      lines.push(`- **[${r.severity.toUpperCase()}] ${r.controlId}** ${r.title} — ${r.citation}`);
    }
    lines.push('');
  }
  lines.push('---');
  lines.push('');
  lines.push(
    '_Auto-generated by modelCardGenerator for EU AI Act Art.11 technical documentation._'
  );
  return lines.join('\n');
}

function buildJson(input: ModelCardInput): string {
  return JSON.stringify(
    {
      schema: 'eu-ai-act-annex-iv',
      version: 1,
      model: {
        name: input.modelName,
        version: input.version,
        owner: input.owner,
        intendedUse: input.intendedUse,
        systemDescription: input.systemDescription,
      },
      governance: {
        euAiActTier: input.governanceAudit.euAiActTier,
        overallScore: input.governanceAudit.overallScore,
        auditedAt: input.governanceAudit.auditedAt,
        frameworkScores: input.governanceAudit.frameworks.map((f) => ({
          framework: f.framework,
          score: f.score,
          pass: f.summary.pass,
          partial: f.summary.partial,
          fail: f.summary.fail,
          unknown: f.summary.unknown,
        })),
      },
      subsystems: input.subsystemScores.map((s) => ({
        name: s.subsystem,
        total: s.total,
        maturity: s.maturity,
        recommendation: s.recommendation,
      })),
      dataSources: input.dataSources,
      limitations: input.limitations,
      humanOversight: input.humanOversight,
      remediation: input.governanceAudit.remediation,
      generatedAt: new Date().toISOString(),
    },
    null,
    2
  );
}
