/**
 * PDF Audit Report Builder — produces a structured document tree that
 * the frontend (or a headless renderer) converts into a PDF for the
 * regulator.
 *
 * Why this exists:
 *   Inspectors want PDFs, not JSON. Today every audit artifact in the
 *   tool is structured data that the MLRO copy-pastes into Word.
 *   That's slow and error-prone — and the resulting document has no
 *   integrity seal.
 *
 *   This module is the PURE document builder. It takes an evidence
 *   bundle + any extras (telemetry excerpt, runbook page, cohort
 *   summary) and returns a `PdfDocument` — a structured tree of
 *   sections, headings, paragraphs, tables, and a signed footer. The
 *   frontend renders this via the browser's print dialog or a
 *   headless PDF library.
 *
 *   By keeping the builder PURE and the renderer SEPARATE we:
 *     - Get deterministic output (same input → same tree)
 *     - Test without a PDF engine
 *     - Let operators swap renderers (browser print, pdfkit,
 *       headless Chrome, wkhtmltopdf) without touching the model
 *     - Produce a content hash on the tree for tamper detection
 *
 *   The integrity hash covers the full tree minus the footer signature
 *   field. Auditors re-hash on receipt and compare.
 *
 * Regulatory basis:
 *   FDL No.10/2025 Art.20-22 (CO reasoned, defensible audit artifact)
 *   FDL No.10/2025 Art.24    (10-year retention — PDF is the retention
 *                              format regulators expect)
 *   Cabinet Res 134/2025 Art.19 (internal review)
 *   FATF Rec 11              (record keeping)
 *   NIST AI RMF 1.0 MANAGE-2 (decision provenance)
 *   EU AI Act Art.14         (human-reviewable output)
 */

import { sha3_512Hex } from './quantumResistantSeal';
import type { EvidenceBundle } from './evidenceBundleExporter';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type PdfBlock =
  | { kind: 'heading'; level: 1 | 2 | 3; text: string }
  | { kind: 'paragraph'; text: string }
  | { kind: 'kv'; pairs: ReadonlyArray<[string, string]> }
  | { kind: 'table'; headers: readonly string[]; rows: readonly (readonly string[])[] }
  | { kind: 'citation'; text: string }
  | { kind: 'pageBreak' };

export interface PdfSection {
  id: string;
  title: string;
  blocks: readonly PdfBlock[];
}

export interface PdfFooter {
  /** ISO timestamp the PDF was built. */
  generatedAtIso: string;
  /** Who generated it. */
  generatedBy: string;
  /** SHA3-512 integrity hash over the tree minus this signature. */
  integrityHashHex: string;
  /** Line regulators look for. */
  attestation: string;
}

export interface PdfDocument {
  schemaVersion: 1;
  title: string;
  subtitle: string;
  /** Front-cover fields rendered on page 1. */
  cover: Readonly<Record<string, string>>;
  /** Ordered sections — one per chapter. */
  sections: readonly PdfSection[];
  footer: PdfFooter;
  /** Regulatory citations shown in the footer of every page. */
  regulatory: readonly string[];
}

// ---------------------------------------------------------------------------
// Canonical JSON for the integrity hash
// ---------------------------------------------------------------------------

function canonicalStringify(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'null';
    return String(value);
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(canonicalStringify).join(',') + ']';
  if (typeof value === 'object') {
    const rec = value as Record<string, unknown>;
    const keys = Object.keys(rec).sort();
    return (
      '{' +
      keys.map((k) => JSON.stringify(k) + ':' + canonicalStringify(rec[k])).join(',') +
      '}'
    );
  }
  return 'null';
}

// ---------------------------------------------------------------------------
// Section builders — pure helpers the outer builder composes
// ---------------------------------------------------------------------------

function buildCoverPairs(bundle: EvidenceBundle, extras: ReportExtras): Record<string, string> {
  return {
    'Tenant': bundle.tenantId,
    'Case ID': bundle.caseId,
    'Verdict at time': bundle.replay?.verdictAtTime ?? 'n/a',
    'Conclusion': bundle.conclusion,
    'Exported at': bundle.exportedAtIso,
    'Evidence hash': bundle.integrity.hashHex.slice(0, 32) + '...',
    'Prepared for': extras.recipient,
    'Generated by': extras.operator,
  };
}

function buildExecutiveSummary(bundle: EvidenceBundle): PdfSection {
  const blocks: PdfBlock[] = [
    { kind: 'heading', level: 2, text: 'Executive summary' },
    { kind: 'paragraph', text: bundle.summary },
    {
      kind: 'kv',
      pairs: [
        ['Conclusion', bundle.conclusion],
        ['Bundle hash', bundle.integrity.hashHex.slice(0, 32) + '...'],
      ],
    },
  ];
  return { id: 'executive-summary', title: 'Executive summary', blocks };
}

function buildVerdictSection(bundle: EvidenceBundle): PdfSection {
  const blocks: PdfBlock[] = [{ kind: 'heading', level: 2, text: 'Decision record' }];
  if (bundle.replay) {
    blocks.push({
      kind: 'kv',
      pairs: [
        ['Verdict', bundle.replay.verdictAtTime],
        ['Confidence', bundle.replay.confidenceAtTime.toFixed(3)],
        ['Power score', String(bundle.replay.powerScoreAtTime ?? 'n/a')],
        ['Decided at', bundle.replay.decidedAtIso],
      ],
    });
  } else {
    blocks.push({ kind: 'paragraph', text: 'Replay tuple not found for this case.' });
  }
  return { id: 'decision-record', title: 'Decision record', blocks };
}

function buildDriftSection(bundle: EvidenceBundle): PdfSection {
  const blocks: PdfBlock[] = [{ kind: 'heading', level: 2, text: 'Regulatory drift' }];
  if (!bundle.drift) {
    blocks.push({
      kind: 'paragraph',
      text: 'No drift report available (replay tuple missing).',
    });
    return { id: 'drift', title: 'Regulatory drift', blocks };
  }
  blocks.push({
    kind: 'kv',
    pairs: [
      ['Clean', String(bundle.drift.clean)],
      ['Top severity', bundle.drift.topSeverity],
      ['Finding count', String(bundle.drift.findings.length)],
    ],
  });
  if (bundle.drift.findings.length > 0) {
    blocks.push({
      kind: 'table',
      headers: ['Key', 'Previous', 'Current', 'Severity'],
      rows: bundle.drift.findings.slice(0, 20).map((f) => [
        f.key,
        String(f.previous),
        String(f.current),
        f.severity,
      ]),
    });
  }
  return { id: 'drift', title: 'Regulatory drift', blocks };
}

function buildCitationsSection(bundle: EvidenceBundle): PdfSection {
  return {
    id: 'citations',
    title: 'Regulatory citations',
    blocks: bundle.citations.map((c) => ({ kind: 'citation', text: c })),
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ReportExtras {
  recipient: string;
  operator: string;
  title?: string;
  subtitle?: string;
  /** Optional extra sections appended after the standard ones. */
  extraSections?: readonly PdfSection[];
  /** Override "now" for tests. */
  now?: () => Date;
}

export function buildAuditReport(
  bundle: EvidenceBundle,
  extras: ReportExtras
): PdfDocument {
  const now = (extras.now ?? (() => new Date()))();
  const sections: PdfSection[] = [
    buildExecutiveSummary(bundle),
    buildVerdictSection(bundle),
    buildDriftSection(bundle),
    ...(extras.extraSections ?? []),
    buildCitationsSection(bundle),
  ];

  const cover = buildCoverPairs(bundle, extras);

  // Pre-integrity document (footer.integrityHashHex placeholder empty).
  const unsigned: Omit<PdfDocument, 'footer'> & {
    footer: Omit<PdfFooter, 'integrityHashHex'>;
  } = {
    schemaVersion: 1,
    title: extras.title ?? 'HAWKEYE STERLING Evidence Pack',
    subtitle: extras.subtitle ?? `Case ${bundle.caseId}`,
    cover,
    sections,
    footer: {
      generatedAtIso: now.toISOString(),
      generatedBy: extras.operator,
      attestation:
        'This PDF is a deterministic render of the HAWKEYE STERLING ' +
        'evidence bundle. The integrity hash below commits every field ' +
        'above. Auditors may re-hash by re-building with the same input ' +
        'and comparing hashes.',
    },
    regulatory: [
      'FDL No.10/2025 Art.20-22',
      'FDL No.10/2025 Art.24',
      'Cabinet Res 134/2025 Art.19',
      'FATF Rec 11',
      'NIST AI RMF 1.0 MANAGE-2',
      'EU AI Act Art.14',
    ],
  };

  // Seal.
  const preimage = 'pdf-audit-report-v1|' + canonicalStringify(unsigned);
  const integrityHashHex = sha3_512Hex(preimage);

  return {
    ...unsigned,
    footer: { ...unsigned.footer, integrityHashHex },
  };
}

export function verifyAuditReportIntegrity(doc: PdfDocument): boolean {
  if (!doc || typeof doc !== 'object') return false;
  if (!doc.footer || typeof doc.footer.integrityHashHex !== 'string') return false;
  const { footer, ...rest } = doc;
  const { integrityHashHex: _hash, ...footerRest } = footer;
  void _hash;
  const unsigned = { ...rest, footer: footerRest };
  const preimage = 'pdf-audit-report-v1|' + canonicalStringify(unsigned);
  return sha3_512Hex(preimage) === footer.integrityHashHex;
}

/**
 * Render the document to plain text — useful for tests and for the
 * "print to terminal" inspector fallback.
 */
export function renderPdfDocumentAsText(doc: PdfDocument): string {
  const lines: string[] = [];
  lines.push('='.repeat(70));
  lines.push(doc.title);
  lines.push(doc.subtitle);
  lines.push('='.repeat(70));
  for (const [k, v] of Object.entries(doc.cover)) {
    lines.push(`${k.padEnd(20)} ${v}`);
  }
  lines.push('');

  for (const section of doc.sections) {
    lines.push('');
    lines.push(section.title.toUpperCase());
    lines.push('-'.repeat(section.title.length));
    for (const block of section.blocks) {
      switch (block.kind) {
        case 'heading':
          lines.push('');
          lines.push(block.text);
          break;
        case 'paragraph':
          lines.push(block.text);
          break;
        case 'kv':
          for (const [k, v] of block.pairs) lines.push(`  ${k.padEnd(24)} ${v}`);
          break;
        case 'table':
          lines.push(block.headers.join(' | '));
          lines.push(block.headers.map(() => '---').join(' | '));
          for (const row of block.rows) lines.push(row.join(' | '));
          break;
        case 'citation':
          lines.push(`  - ${block.text}`);
          break;
        case 'pageBreak':
          lines.push('\n--- page break ---\n');
          break;
      }
    }
  }

  lines.push('');
  lines.push('='.repeat(70));
  lines.push(`Generated by: ${doc.footer.generatedBy}`);
  lines.push(`Generated at: ${doc.footer.generatedAtIso}`);
  lines.push(`Integrity   : ${doc.footer.integrityHashHex.slice(0, 32)}...`);
  lines.push(doc.footer.attestation);
  lines.push('Citations:');
  for (const c of doc.regulatory) lines.push(`  - ${c}`);
  lines.push('='.repeat(70));
  return lines.join('\n');
}

// Exports for tests.
export const __test__ = { canonicalStringify, buildCoverPairs };
