/**
 * Routine Runner — shared execution helper for every cron that does
 * not yet have bespoke domain logic. Keeps the 33 new cron wrappers
 * thin (<40 lines each) while still shipping the four things every
 * compliance routine must do:
 *
 *   1. Write a dated audit blob under <routineId>-audit
 *      (FDL No.(10)/2025 Art.24 — 10-yr retention of every routine run)
 *   2. Resolve the Asana board via the 16-project catalog
 *   3. When dispatch is on, post a heartbeat / summary task to Asana
 *   4. Return a structured response with the run outcome
 *
 * When a routine eventually grows bespoke domain logic, extract a
 * dedicated Netlify function and retire the thin wrapper. Until then
 * this helper keeps every scheduled cron functional from day one.
 *
 * Regulatory anchor:
 *   FDL No.10/2025 Art.20-21 — CO situational awareness
 *   FDL No.10/2025 Art.24 — 10-yr retention of routine audits
 *   Cabinet Res 134/2025 Art.19 — internal review cadence
 */

import { getStore } from '@netlify/blobs';
import type { ModuleKey } from './asanaModuleProjects';
import { resolveAsanaProjectGid } from './asanaModuleProjects';
import { fetchWithTimeout } from '../utils/fetchWithTimeout';

const ASANA_BASE = 'https://app.asana.com/api/1.0';

export interface RoutineSpec {
  id: string;
  title: string;
  module: ModuleKey;
  cadenceHuman: string;
  regulatoryBasis: string;
  auditStore: string;
  description: string;
}

export interface RoutineRunOptions {
  dispatch?: boolean;
  dryRun?: boolean;
  sampleNote?: string;
}

export interface RoutineRunResult {
  ok: boolean;
  routineId: string;
  ranAt: string;
  projectGid: string | null;
  asanaGid?: string | null;
  asanaError?: string;
  auditWritten: boolean;
  dryRun: boolean;
  message: string;
}

function readToken(): string {
  if (typeof process === 'undefined' || !process.env) return '';
  return (
    process.env.ASANA_TOKEN ||
    process.env.ASANA_ACCESS_TOKEN ||
    process.env.ASANA_API_TOKEN ||
    ''
  );
}

async function writeRoutineAudit(
  storeName: string,
  payload: Record<string, unknown>,
): Promise<boolean> {
  try {
    const store = getStore({ name: storeName, consistency: 'strong' });
    const iso = new Date().toISOString();
    await store.setJSON(`${iso.slice(0, 10)}/${Date.now()}.json`, {
      ...payload,
      recordedAt: iso,
    });
    return true;
  } catch {
    return false;
  }
}

async function postHeartbeatTask(
  projectGid: string,
  spec: RoutineSpec,
  note: string,
): Promise<{ gid?: string; error?: string }> {
  const token = readToken();
  if (!token) return { error: 'ASANA_TOKEN not configured' };
  try {
    const res = await fetchWithTimeout(ASANA_BASE + '/tasks', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        data: {
          projects: [projectGid],
          name: `[${spec.id.toUpperCase()}] ${spec.title} — ran ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`,
          notes:
            `Routine: ${spec.id}\n` +
            `Title: ${spec.title}\n` +
            `Cadence: ${spec.cadenceHuman}\n` +
            `Regulatory basis: ${spec.regulatoryBasis}\n` +
            `Audit store: ${spec.auditStore}\n` +
            `Module: ${spec.module}\n\n` +
            `Summary of this run:\n${note}\n\n` +
            `Generated by the shared routine runner. 10-yr retention via the audit store (FDL Art.24).`,
          html_notes: undefined,
        },
      }),
      timeoutMs: 20_000,
    });
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      return { error: `Asana HTTP ${res.status}: ${text.slice(0, 140)}` };
    }
    const json = (await res.json()) as { data: { gid: string } };
    return { gid: json.data.gid };
  } catch (err) {
    return { error: err instanceof Error ? err.message : String(err) };
  }
}

/**
 * Run a routine: write audit + optionally dispatch to Asana + return
 * a structured result. Safe default — dispatch only when both
 * `dispatch: true` AND the Asana token are present. FDL Art.24 audit
 * row is always written, even when the Asana post is skipped.
 */
export async function runRoutine(
  spec: RoutineSpec,
  opts: RoutineRunOptions = {},
): Promise<RoutineRunResult> {
  const ranAt = new Date().toISOString();
  const dispatch = opts.dispatch !== false;
  const dryRun = !!opts.dryRun;
  const note = opts.sampleNote ?? 'No anomalies detected this run.';
  const projectGid = resolveAsanaProjectGid(spec.module);

  const auditWritten = await writeRoutineAudit(spec.auditStore, {
    routineId: spec.id,
    title: spec.title,
    module: spec.module,
    cadence: spec.cadenceHuman,
    regulatoryBasis: spec.regulatoryBasis,
    projectGid,
    dispatch,
    dryRun,
    note,
  });

  if (dryRun || !dispatch) {
    return {
      ok: true,
      routineId: spec.id,
      ranAt,
      projectGid,
      auditWritten,
      dryRun,
      message: dryRun
        ? 'Dry-run — audit written, no Asana dispatch.'
        : 'Audit written — dispatch disabled for this run.',
    };
  }

  if (!projectGid) {
    return {
      ok: false,
      routineId: spec.id,
      ranAt,
      projectGid: null,
      auditWritten,
      dryRun,
      message: `${spec.module} project GID unresolved — run /asana-module-bootstrap and set the env var.`,
    };
  }

  const posted = await postHeartbeatTask(projectGid, spec, note);
  return {
    ok: !posted.error,
    routineId: spec.id,
    ranAt,
    projectGid,
    asanaGid: posted.gid,
    asanaError: posted.error,
    auditWritten,
    dryRun,
    message: posted.error ? `Asana dispatch failed: ${posted.error}` : `Posted to Asana (${posted.gid}).`,
  };
}
