/**
 * Real-Time AML Transaction Monitoring Engine
 *
 * Adapts risk management patterns from hyperliquid-trading-agent:
 * - Circuit breakers: pause alerting when anomalous volume spikes occur
 * - Velocity tracking: monitor transaction frequency per customer
 * - Behavioral profiling: detect deviations from customer baseline
 * - Cumulative exposure: track rolling windows of activity
 * - Mandatory escalation: hard-enforced rules that cannot be overridden
 *
 * Extends the existing TMRule/TMAlert framework in src/risk/transactionMonitoring.ts
 * with stateful, real-time monitoring capabilities.
 *
 * Regulatory refs:
 * - FDL No.10/2025 Art.15-16 (thresholds, reporting)
 * - Cabinet Res 134/2025 Art.5 (risk appetite), Art.16 (cross-border)
 * - FATF Rec 20-23 (DPMS monitoring)
 * - MoE Circular 08/AML/2021 (DPMS-specific)
 */

import {
  DPMS_CASH_THRESHOLD_AED,
  STRUCTURING_CUMULATIVE_PCT,
  CROSS_BORDER_CASH_THRESHOLD_AED,
} from '../domain/constants';
import type { TMAlert, TransactionInput } from '../risk/transactionMonitoring';
import { runTransactionMonitoring } from '../risk/transactionMonitoring';

// ─── Types ─────────────────────────────────────────────────────────────────

export interface CustomerProfile {
  customerId: string;
  customerName: string;
  riskRating: 'low' | 'medium' | 'high';
  /** Average transaction amount (rolling 90-day) */
  avgTransactionAmount: number;
  /** Average transactions per month */
  avgTransactionsPerMonth: number;
  /** Typical payment methods */
  typicalPaymentMethods: string[];
  /** Typical counterparty countries */
  typicalCountries: string[];
  /** Last transaction date (ISO) */
  lastTransactionDate: string | null;
  /** Date profile was last recalculated */
  profileUpdatedAt: string;
}

export interface VelocityRecord {
  customerId: string;
  /** Transactions in the current rolling window */
  transactions: Array<{
    amount: number;
    timestamp: string;
    currency: string;
  }>;
}

export interface CircuitBreakerState {
  /** Whether the circuit breaker is tripped */
  tripped: boolean;
  /** Reason for tripping */
  reason: string;
  /** When the breaker was tripped */
  trippedAt: string | null;
  /** When the breaker should auto-reset */
  resetsAt: string | null;
  /** Number of alerts suppressed while tripped */
  suppressedAlerts: number;
}

export interface EnhancedTMAlert extends TMAlert {
  /** Unique alert ID */
  alertId: string;
  /** Customer ID */
  customerId: string;
  /** Timestamp when alert was generated */
  generatedAt: string;
  /** Whether this alert was generated by behavioral analysis */
  isBehavioral: boolean;
  /** Deviation from customer profile (0-1, higher = more anomalous) */
  anomalyScore: number;
  /** Related alerts in the same session */
  relatedAlertIds: string[];
}

export interface MonitoringSession {
  /** Session ID */
  sessionId: string;
  /** When monitoring started */
  startedAt: string;
  /** Total transactions processed */
  transactionsProcessed: number;
  /** Total alerts generated */
  alertsGenerated: number;
  /** Circuit breaker state */
  circuitBreaker: CircuitBreakerState;
}

// ─── Engine Configuration ──────────────────────────────────────────────────

export interface EngineConfig {
  /** Rolling window for velocity tracking (hours) */
  velocityWindowHours: number;
  /** Max transactions in velocity window before alert */
  velocityMaxTransactions: number;
  /** Deviation multiplier for behavioral alerts (e.g., 3x = alert if amount > 3x average) */
  behavioralDeviationMultiplier: number;
  /** Circuit breaker: max alerts per hour before tripping */
  circuitBreakerAlertThreshold: number;
  /** Circuit breaker: auto-reset duration (minutes) */
  circuitBreakerResetMinutes: number;
  /** Cumulative amount window (days) */
  cumulativeWindowDays: number;
}

const DEFAULT_ENGINE_CONFIG: EngineConfig = {
  velocityWindowHours: 24,
  velocityMaxTransactions: 10,
  behavioralDeviationMultiplier: 3,
  circuitBreakerAlertThreshold: 50,
  circuitBreakerResetMinutes: 30,
  cumulativeWindowDays: 30,
};

// ─── Transaction Monitoring Engine ─────────────────────────────────────────

export class TransactionMonitoringEngine {
  private profiles: Map<string, CustomerProfile> = new Map();
  private velocityRecords: Map<string, VelocityRecord> = new Map();
  private circuitBreaker: CircuitBreakerState;
  private session: MonitoringSession;
  private recentAlerts: EnhancedTMAlert[] = [];
  private alertsThisHour: number = 0;
  private hourStart: number = Date.now();
  private config: EngineConfig;
  private alertCounter: number = 0;

  constructor(config?: Partial<EngineConfig>) {
    this.config = { ...DEFAULT_ENGINE_CONFIG, ...config };
    this.circuitBreaker = {
      tripped: false,
      reason: '',
      trippedAt: null,
      resetsAt: null,
      suppressedAlerts: 0,
    };
    this.session = {
      sessionId: `TMS-${Date.now()}`,
      startedAt: new Date().toISOString(),
      transactionsProcessed: 0,
      alertsGenerated: 0,
      circuitBreaker: this.circuitBreaker,
    };
  }

  // ─── Profile Management ────────────────────────────────────────────────

  /**
   * Load or update a customer's behavioral profile.
   * Profiles should be computed from historical transaction data.
   */
  loadProfile(profile: CustomerProfile): void {
    this.profiles.set(profile.customerId, profile);
  }

  /**
   * Get a customer's current profile, or null if unknown.
   */
  getProfile(customerId: string): CustomerProfile | null {
    return this.profiles.get(customerId) ?? null;
  }

  // ─── Core Monitoring ───────────────────────────────────────────────────

  /**
   * Process a transaction through the full monitoring pipeline.
   *
   * Pipeline (adapted from hyperliquid-trading-agent's run_loop):
   * 1. Run existing TM rules (from transactionMonitoring.ts)
   * 2. Check velocity (transaction frequency)
   * 3. Check behavioral deviation (amount vs profile)
   * 4. Check cumulative exposure (rolling window)
   * 5. Check cross-border thresholds
   * 6. Apply circuit breaker logic
   * 7. Return combined alerts
   *
   * All checks are hard-enforced — no override possible.
   */
  processTransaction(tx: TransactionInput, customerId: string): EnhancedTMAlert[] {
    this.session.transactionsProcessed++;
    this.checkCircuitBreakerReset();

    const allAlerts: EnhancedTMAlert[] = [];
    const now = new Date().toISOString();

    // Step 1: Run existing rule-based monitoring
    const ruleAlerts = runTransactionMonitoring(tx);
    for (const alert of ruleAlerts) {
      allAlerts.push(this.enhanceAlert(alert, customerId, now, false, 0));
    }

    // Step 2: Velocity check
    const velocityAlert = this.checkVelocity(tx, customerId, now);
    if (velocityAlert) allAlerts.push(velocityAlert);

    // Step 3: Behavioral deviation check
    const behavioralAlert = this.checkBehavioralDeviation(tx, customerId, now);
    if (behavioralAlert) allAlerts.push(behavioralAlert);

    // Step 4: Cumulative exposure check
    const cumulativeAlert = this.checkCumulativeExposure(tx, customerId, now);
    if (cumulativeAlert) allAlerts.push(cumulativeAlert);

    // Step 5: Cross-border threshold check
    const crossBorderAlert = this.checkCrossBorder(tx, customerId, now);
    if (crossBorderAlert) allAlerts.push(crossBorderAlert);

    // Step 6: Update velocity records
    this.updateVelocityRecord(customerId, tx);

    // Step 7: Link related alerts
    const alertIds = allAlerts.map((a) => a.alertId);
    for (const alert of allAlerts) {
      alert.relatedAlertIds = alertIds.filter((id) => id !== alert.alertId);
    }

    // Step 8: Circuit breaker check
    if (this.circuitBreaker.tripped) {
      // Critical alerts always pass through even when circuit breaker is tripped
      const critical = allAlerts.filter((a) => a.severity === 'critical');
      this.circuitBreaker.suppressedAlerts += allAlerts.length - critical.length;
      this.session.alertsGenerated += critical.length;
      this.recentAlerts.push(...critical);
      return critical;
    }

    // Update alert rate tracking
    this.trackAlertRate(allAlerts.length);

    this.session.alertsGenerated += allAlerts.length;
    this.recentAlerts.push(...allAlerts);

    return allAlerts;
  }

  // ─── Velocity Monitoring ───────────────────────────────────────────────

  /**
   * Check transaction frequency within the rolling window.
   * Adapted from hyperliquid-trading-agent's check_concurrent_positions.
   */
  private checkVelocity(
    tx: TransactionInput,
    customerId: string,
    now: string
  ): EnhancedTMAlert | null {
    const record = this.velocityRecords.get(customerId);
    if (!record) return null;

    const windowStart = Date.now() - this.config.velocityWindowHours * 60 * 60 * 1000;
    const recentTxs = record.transactions.filter(
      (t) => new Date(t.timestamp).getTime() > windowStart
    );

    if (recentTxs.length >= this.config.velocityMaxTransactions) {
      const totalAmount = recentTxs.reduce((sum, t) => sum + t.amount, 0);
      return this.enhanceAlert(
        {
          ruleId: 'structuring',
          ruleName: 'High Transaction Velocity',
          severity: 'high',
          message: `${recentTxs.length} transactions in ${this.config.velocityWindowHours}h window (total: AED ${totalAmount.toLocaleString()}). Customer: ${tx.customerName}, latest: AED ${tx.amount.toLocaleString()}.`,
          regulatoryRef: 'FDL No.10/2025 Art.15, MoE DPMS Guidance',
        },
        customerId,
        now,
        true,
        Math.min(1, recentTxs.length / (this.config.velocityMaxTransactions * 2))
      );
    }

    return null;
  }

  // ─── Behavioral Deviation ──────────────────────────────────────────────

  /**
   * Detect transactions that deviate significantly from customer's baseline.
   * Adapted from hyperliquid-trading-agent's check_daily_drawdown pattern.
   */
  private checkBehavioralDeviation(
    tx: TransactionInput,
    customerId: string,
    now: string
  ): EnhancedTMAlert | null {
    const profile = this.profiles.get(customerId);
    if (!profile || profile.avgTransactionAmount === 0) return null;

    const deviation = tx.amount / profile.avgTransactionAmount;
    const threshold = this.config.behavioralDeviationMultiplier;

    if (deviation >= threshold) {
      const anomalyScore = Math.min(1, (deviation - threshold) / threshold);
      return this.enhanceAlert(
        {
          ruleId: 'profile-mismatch',
          ruleName: 'Behavioral Deviation — Amount Anomaly',
          severity: deviation >= threshold * 2 ? 'critical' : 'high',
          message: `Transaction AED ${tx.amount.toLocaleString()} is ${deviation.toFixed(1)}x customer average (AED ${profile.avgTransactionAmount.toLocaleString()}). Customer: ${tx.customerName}.`,
          regulatoryRef: 'Cabinet Res 134/2025 Art.16, UAE NRA 2024',
        },
        customerId,
        now,
        true,
        anomalyScore
      );
    }

    // Check payment method deviation
    if (
      tx.paymentMethod &&
      profile.typicalPaymentMethods.length > 0 &&
      !profile.typicalPaymentMethods.includes(tx.paymentMethod)
    ) {
      return this.enhanceAlert(
        {
          ruleId: 'profile-mismatch',
          ruleName: 'Behavioral Deviation — Unusual Payment Method',
          severity: 'medium',
          message: `Payment via "${tx.paymentMethod}" is unusual for this customer (typical: ${profile.typicalPaymentMethods.join(', ')}). Customer: ${tx.customerName}, Amount: AED ${tx.amount.toLocaleString()}.`,
          regulatoryRef: 'Cabinet Res 134/2025 Art.16',
        },
        customerId,
        now,
        true,
        0.4
      );
    }

    return null;
  }

  // ─── Cumulative Exposure ───────────────────────────────────────────────

  /**
   * Track cumulative transaction amounts approaching thresholds.
   * Adapted from hyperliquid-trading-agent's check_total_exposure.
   */
  private checkCumulativeExposure(
    tx: TransactionInput,
    customerId: string,
    now: string
  ): EnhancedTMAlert | null {
    const record = this.velocityRecords.get(customerId);
    if (!record) return null;

    const windowStart = Date.now() - this.config.cumulativeWindowDays * 24 * 60 * 60 * 1000;
    const recentTxs = record.transactions.filter(
      (t) => new Date(t.timestamp).getTime() > windowStart
    );

    const cumulative = recentTxs.reduce((sum, t) => sum + t.amount, 0) + tx.amount;
    const structuringThreshold = DPMS_CASH_THRESHOLD_AED * STRUCTURING_CUMULATIVE_PCT;

    // Check if cumulative amount is approaching or exceeding threshold
    // while individual transactions remain below it
    if (
      cumulative >= DPMS_CASH_THRESHOLD_AED &&
      tx.amount < DPMS_CASH_THRESHOLD_AED &&
      recentTxs.length >= 2
    ) {
      return this.enhanceAlert(
        {
          ruleId: 'structuring',
          ruleName: 'Cumulative Exposure — Threshold Breach',
          severity: 'critical',
          message: `Cumulative amount AED ${cumulative.toLocaleString()} exceeds AED ${DPMS_CASH_THRESHOLD_AED.toLocaleString()} threshold over ${this.config.cumulativeWindowDays} days across ${recentTxs.length + 1} transactions. Individual amounts below threshold. Customer: ${tx.customerName}. Requires CTR filing.`,
          regulatoryRef: 'FDL No.10/2025 Art.15-16, FATF Rec 22, MoE Circular 08/AML/2021',
        },
        customerId,
        now,
        false,
        Math.min(1, cumulative / (DPMS_CASH_THRESHOLD_AED * 2))
      );
    }

    // Warning: approaching threshold
    if (
      cumulative >= structuringThreshold &&
      cumulative < DPMS_CASH_THRESHOLD_AED &&
      recentTxs.length >= 2
    ) {
      return this.enhanceAlert(
        {
          ruleId: 'threshold-avoidance',
          ruleName: 'Cumulative Exposure — Approaching Threshold',
          severity: 'high',
          message: `Cumulative amount AED ${cumulative.toLocaleString()} approaching AED ${DPMS_CASH_THRESHOLD_AED.toLocaleString()} threshold (${Math.round((cumulative / DPMS_CASH_THRESHOLD_AED) * 100)}%). Customer: ${tx.customerName}.`,
          regulatoryRef: 'FDL No.10/2025 Art.15-16, FATF Rec 22',
        },
        customerId,
        now,
        false,
        0.6
      );
    }

    return null;
  }

  // ─── Cross-Border Detection ────────────────────────────────────────────

  /**
   * Check cross-border cash/BNI declaration threshold.
   */
  private checkCrossBorder(
    tx: TransactionInput,
    customerId: string,
    now: string
  ): EnhancedTMAlert | null {
    if (
      tx.originCountry &&
      tx.destinationCountry &&
      tx.originCountry !== tx.destinationCountry &&
      tx.amount >= CROSS_BORDER_CASH_THRESHOLD_AED
    ) {
      return this.enhanceAlert(
        {
          ruleId: 'offshore-routing',
          ruleName: 'Cross-Border Declaration Required',
          severity: 'critical',
          message: `Cross-border transaction AED ${tx.amount.toLocaleString()} exceeds AED ${CROSS_BORDER_CASH_THRESHOLD_AED.toLocaleString()} declaration threshold. Route: ${tx.originCountry} → ${tx.destinationCountry}. Customer: ${tx.customerName}. Declaration required per FDL Art.17.`,
          regulatoryRef: 'FDL No.10/2025 Art.17, Cabinet Res 134/2025 Art.16',
        },
        customerId,
        now,
        false,
        0.8
      );
    }

    return null;
  }

  // ─── Circuit Breaker ───────────────────────────────────────────────────

  /**
   * Circuit breaker — adapted from hyperliquid-trading-agent's daily_loss_circuit_breaker.
   *
   * Trips when alert volume exceeds threshold (indicates systemic issue
   * like batch processing, data error, or actual attack requiring investigation
   * before continuing normal operations).
   *
   * Critical alerts always pass through even when tripped.
   */
  private trackAlertRate(newAlerts: number): void {
    const now = Date.now();

    // Reset hourly counter
    if (now - this.hourStart > 60 * 60 * 1000) {
      this.alertsThisHour = 0;
      this.hourStart = now;
    }

    this.alertsThisHour += newAlerts;

    if (
      this.alertsThisHour >= this.config.circuitBreakerAlertThreshold &&
      !this.circuitBreaker.tripped
    ) {
      const resetsAt = new Date(
        now + this.config.circuitBreakerResetMinutes * 60 * 1000
      ).toISOString();
      this.circuitBreaker = {
        tripped: true,
        reason: `Alert volume exceeded ${this.config.circuitBreakerAlertThreshold}/hour (${this.alertsThisHour} alerts). Possible systemic issue — investigate before continuing. Critical alerts still pass through.`,
        trippedAt: new Date().toISOString(),
        resetsAt,
        suppressedAlerts: 0,
      };
      this.session.circuitBreaker = this.circuitBreaker;
    }
  }

  private checkCircuitBreakerReset(): void {
    if (
      this.circuitBreaker.tripped &&
      this.circuitBreaker.resetsAt &&
      new Date(this.circuitBreaker.resetsAt).getTime() <= Date.now()
    ) {
      this.circuitBreaker = {
        tripped: false,
        reason: '',
        trippedAt: null,
        resetsAt: null,
        suppressedAlerts: 0,
      };
      this.session.circuitBreaker = this.circuitBreaker;
    }
  }

  /**
   * Manually reset the circuit breaker (e.g., after investigation).
   */
  resetCircuitBreaker(): void {
    this.circuitBreaker = {
      tripped: false,
      reason: '',
      trippedAt: null,
      resetsAt: null,
      suppressedAlerts: 0,
    };
    this.session.circuitBreaker = this.circuitBreaker;
  }

  // ─── Helpers ───────────────────────────────────────────────────────────

  private updateVelocityRecord(customerId: string, tx: TransactionInput): void {
    let record = this.velocityRecords.get(customerId);
    if (!record) {
      record = { customerId, transactions: [] };
      this.velocityRecords.set(customerId, record);
    }

    record.transactions.push({
      amount: tx.amount,
      timestamp: new Date().toISOString(),
      currency: tx.currency,
    });

    // Prune old transactions outside the window
    const windowStart = Date.now() - this.config.cumulativeWindowDays * 24 * 60 * 60 * 1000;
    record.transactions = record.transactions.filter(
      (t) => new Date(t.timestamp).getTime() > windowStart
    );
  }

  private enhanceAlert(
    baseAlert: TMAlert,
    customerId: string,
    now: string,
    isBehavioral: boolean,
    anomalyScore: number
  ): EnhancedTMAlert {
    this.alertCounter++;
    return {
      ...baseAlert,
      alertId: `TMA-${this.session.sessionId}-${this.alertCounter}`,
      customerId,
      generatedAt: now,
      isBehavioral,
      anomalyScore: Math.round(anomalyScore * 100) / 100,
      relatedAlertIds: [],
    };
  }

  // ─── Reporting ─────────────────────────────────────────────────────────

  /**
   * Get the current monitoring session summary.
   */
  getSessionSummary(): MonitoringSession {
    return { ...this.session, circuitBreaker: { ...this.circuitBreaker } };
  }

  /**
   * Get recent alerts (most recent first), optionally filtered by severity.
   */
  getRecentAlerts(limit = 100, severity?: 'medium' | 'high' | 'critical'): EnhancedTMAlert[] {
    let alerts = [...this.recentAlerts];
    if (severity) {
      alerts = alerts.filter((a) => a.severity === severity);
    }
    return alerts.slice(-limit).reverse();
  }

  /**
   * Get risk summary for a specific customer.
   * Adapted from hyperliquid-trading-agent's get_risk_summary.
   */
  getCustomerRiskSummary(customerId: string): {
    customerId: string;
    profile: CustomerProfile | null;
    alertCount: number;
    criticalAlerts: number;
    highAlerts: number;
    behavioralAlerts: number;
    avgAnomalyScore: number;
    velocityRecord: VelocityRecord | null;
    cumulativeAmount30d: number;
  } {
    const profile = this.profiles.get(customerId) ?? null;
    const alerts = this.recentAlerts.filter((a) => a.customerId === customerId);
    const behavioral = alerts.filter((a) => a.isBehavioral);
    const record = this.velocityRecords.get(customerId) ?? null;

    const windowStart = Date.now() - 30 * 24 * 60 * 60 * 1000;
    const cumulative = record
      ? record.transactions
          .filter((t) => new Date(t.timestamp).getTime() > windowStart)
          .reduce((sum, t) => sum + t.amount, 0)
      : 0;

    return {
      customerId,
      profile,
      alertCount: alerts.length,
      criticalAlerts: alerts.filter((a) => a.severity === 'critical').length,
      highAlerts: alerts.filter((a) => a.severity === 'high').length,
      behavioralAlerts: behavioral.length,
      avgAnomalyScore:
        behavioral.length > 0
          ? Math.round(
              (behavioral.reduce((s, a) => s + a.anomalyScore, 0) / behavioral.length) * 100
            ) / 100
          : 0,
      velocityRecord: record,
      cumulativeAmount30d: cumulative,
    };
  }
}
