#!/usr/bin/env node
/**
 * Compliance Analyzer — One-Shot Setup Wizard.
 *
 * Run with: npm run setup
 *
 * What this does:
 *   1. Auto-generates every secret that needs no human input
 *      (HAWKEYE_BRAIN_TOKEN, AUTH_SIGNING_SECRET, HAWKEYE_APPROVER_KEYS)
 *   2. Prompts for the 3 values only Asana can give you
 *      (ASANA_TOKEN, ASANA_WORKSPACE_GID, ASANA_AI_GOVERNANCE_PROJECT_GID)
 *   3. Stubs every paid integration so the system runs in safe
 *      plan-only mode (EOCN, GOAML, BANKING, REUTERS, TEAMS) —
 *      you can swap them later without touching any code
 *   4. Writes .env at the repo root
 *   5. Prints the EXACT 3 commands to push everything to Netlify
 *
 * Zero dependencies — uses Node built-ins only. Safe to run multiple
 * times: existing values in .env are kept, only missing keys are added.
 */

import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = resolve(__dirname, '..', '.env');

// ─── helpers ────────────────────────────────────────────────────────────────

/**
 * Defensive URL normalizer — mirrors src/utils/normalizeBrainUrl.ts.
 * Inlined here because this file is plain JS (.mjs) and cannot
 * import from the TypeScript source tree at runtime. If you edit
 * the logic, also edit src/utils/normalizeBrainUrl.ts to keep them
 * in sync. Covers: trailing slashes, trailing dots, whitespace,
 * missing scheme, bare-scheme fragments.
 */
const CANONICAL_BRAIN_URL = 'https://hawkeye-sterling-v2.netlify.app';
function normalizeBrainUrl(raw) {
  if (raw === undefined || raw === null) return CANONICAL_BRAIN_URL;
  let u = String(raw).trim();
  if (u.length === 0) return CANONICAL_BRAIN_URL;
  if (/^https?:?\/?\/?$/i.test(u)) return CANONICAL_BRAIN_URL;
  if (!/^https?:\/\//i.test(u)) u = 'https://' + u;
  while (u.length > 0 && (u.endsWith('/') || u.endsWith('.'))) {
    u = u.slice(0, -1);
  }
  if (/^https?:?\/?\/?$/i.test(u)) return CANONICAL_BRAIN_URL;
  return u;
}

function hex(bytes) {
  return randomBytes(bytes).toString('hex');
}

/**
 * Strip a single-quote wrapper added by quoteEnvValue. Inverse of
 * the escape rule — handles the bash '\'' → ' unescape so a
 * round-trip through writeEnvFile + readExistingEnv preserves
 * arbitrary string values verbatim.
 */
function unquoteEnvValue(raw) {
  if (raw.length >= 2 && raw.startsWith("'") && raw.endsWith("'")) {
    return raw.slice(1, -1).replace(/'\\''/g, "'");
  }
  // Tolerate double-quoted values written by hand.
  if (raw.length >= 2 && raw.startsWith('"') && raw.endsWith('"')) {
    return raw.slice(1, -1);
  }
  return raw;
}

function readExistingEnv() {
  if (!existsSync(ENV_PATH)) return {};
  const text = readFileSync(ENV_PATH, 'utf8');
  const map = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = unquoteEnvValue(line.slice(eq + 1).trim());
    map[key] = value;
  }
  return map;
}

/**
 * Quote a value for safe inclusion in a shell-sourceable .env file.
 * Bare values without whitespace or special characters stay unquoted
 * for readability (e.g. `ASANA_TOKEN=tok123`). Values containing
 * whitespace, quotes, or shell metacharacters are wrapped in
 * single quotes with internal single quotes escaped via the
 * '\'' bash idiom. This guarantees `set -a; source .env; set +a`
 * never explodes on values like `ASANA_DEFAULT_ASSIGNEE_NAME=Luisa Fernanda`.
 */
function quoteEnvValue(value) {
  if (value === '' || value === undefined || value === null) return '';
  const str = String(value);
  // Bare identifier — safe unquoted.
  if (/^[A-Za-z0-9_./:@+\-,=]+$/.test(str)) return str;
  // Otherwise single-quote the whole thing and escape any embedded single quotes.
  const escaped = str.replace(/'/g, "'\\''");
  return `'${escaped}'`;
}

function writeEnvFile(env) {
  const lines = [
    '# Compliance Analyzer .env — generated by `npm run setup`.',
    `# Generated at ${new Date().toISOString()}`,
    '# Edit any value by hand — re-running setup will keep your edits.',
    '# Values with spaces are single-quoted so `source .env` works.',
    '',
  ];
  const sections = [
    [
      'Asana (REQUIRED)',
      [
        'ASANA_TOKEN',
        'ASANA_WORKSPACE_GID',
        'ASANA_PROXY_URL',
        'ASANA_DEFAULT_ASSIGNEE_NAME',
        'ASANA_SCREENINGS_PROJECT_GID',
        'ASANA_AI_GOVERNANCE_PROJECT_GID',
        'PUBLIC_BASE_URL',
      ],
    ],
    [
      'Server-side auth (REQUIRED, auto-generated)',
      [
        'HAWKEYE_BRAIN_TOKEN',
        'HAWKEYE_APPROVER_KEYS',
        'HAWKEYE_SOLO_MLRO_MODE',
        'HAWKEYE_SOLO_MLRO_COOLDOWN_HOURS',
        'AUTH_SIGNING_SECRET',
        'HAWKEYE_BRAIN_URL',
      ],
    ],
    [
      'Asana custom field GIDs (run `npm run asana:bootstrap:cf -- --apply` to populate)',
      [
        'ASANA_CF_RISK_LEVEL_GID',
        'ASANA_CF_RISK_LEVEL_CRITICAL',
        'ASANA_CF_RISK_LEVEL_HIGH',
        'ASANA_CF_RISK_LEVEL_MEDIUM',
        'ASANA_CF_RISK_LEVEL_LOW',
        'ASANA_CF_VERDICT_GID',
        'ASANA_CF_VERDICT_PASS',
        'ASANA_CF_VERDICT_FLAG',
        'ASANA_CF_VERDICT_ESCALATE',
        'ASANA_CF_VERDICT_FREEZE',
        'ASANA_CF_CASE_ID_GID',
        'ASANA_CF_DEADLINE_TYPE_GID',
        'ASANA_CF_DEADLINE_TYPE_STR',
        'ASANA_CF_DEADLINE_TYPE_CTR',
        'ASANA_CF_DEADLINE_TYPE_CNMR',
        'ASANA_CF_DEADLINE_TYPE_DPMSR',
        'ASANA_CF_DEADLINE_TYPE_EOCN',
        'ASANA_CF_DAYS_REMAINING_GID',
        'ASANA_CF_CONFIDENCE_GID',
        'ASANA_CF_REGULATION_GID',
        'ASANA_CF_CUSTOMER_NAME_GID',
        'ASANA_CF_JURISDICTION_GID',
        'ASANA_CF_UBO_COUNT_GID',
        'ASANA_CF_PEP_FLAG_GID',
        'ASANA_CF_PEP_FLAG_CLEAR',
        'ASANA_CF_PEP_FLAG_POTENTIAL',
        'ASANA_CF_PEP_FLAG_MATCH',
        'ASANA_CF_MANUAL_ACTION_GID',
        'ASANA_CF_MANUAL_ACTION_PENDING',
        'ASANA_CF_MANUAL_ACTION_DONE',
      ],
    ],
    [
      'Cross-project mirror destinations (create projects manually in Asana, paste GIDs here)',
      [
        'ASANA_CENTRAL_MLRO_PROJECT_GID',
        'ASANA_AUDIT_LOG_PROJECT_GID',
        'ASANA_INSPECTOR_PROJECT_GID',
        'ASANA_INSPECTOR_TEAM_GID',
      ],
    ],
    [
      'Notification bridge',
      ['TEAMS_WEBHOOK_URL', 'EMAIL_SERVICE_URL', 'EMAIL_FROM', 'EMAIL_TO_CO'],
    ],
    [
      'Regulatory feeds (STUB-OK — set to a real URL/key when available)',
      ['EOCN_FEED_URL', 'GOAML_PORTAL_API_KEY', 'GOAML_PORTAL_BASE_URL'],
    ],
    ['Banking rail (STUB-OK)', ['BANKING_FREEZE_API_KEY', 'BANKING_FREEZE_BASE_URL']],
    [
      'Spot price feeds (STUB-OK)',
      ['REUTERS_REFINITIV_API_KEY', 'REUTERS_REFINITIV_BASE_URL', 'METAL_PRICE_API_KEY'],
    ],
    [
      'LLM providers (optional)',
      ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'GOOGLE_AI_API_KEY', 'OPENROUTER_API_KEY'],
    ],
  ];
  for (const [title, keys] of sections) {
    lines.push(`# ─── ${title} ───`);
    for (const key of keys) {
      lines.push(`${key}=${quoteEnvValue(env[key])}`);
    }
    lines.push('');
  }
  writeFileSync(ENV_PATH, lines.join('\n'), { mode: 0o600 });
}

// ─── prompts ────────────────────────────────────────────────────────────────

async function ask(rl, prompt, fallback) {
  const display = fallback ? `${prompt} [${fallback}]: ` : `${prompt}: `;
  const answer = (await rl.question(display)).trim();
  return answer || fallback || '';
}

async function confirm(rl, prompt, defaultYes = true) {
  const suffix = defaultYes ? '[Y/n]' : '[y/N]';
  const answer = (await rl.question(`${prompt} ${suffix} `)).trim().toLowerCase();
  if (!answer) return defaultYes;
  return answer === 'y' || answer === 'yes';
}

// ─── main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log('');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('  Compliance Analyzer — One-Shot Setup Wizard');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('');
  console.log('This wizard will:');
  console.log('  1. Auto-generate every secret that needs no human input');
  console.log('  2. Ask you for 3 values only Asana can give you');
  console.log('  3. Stub paid integrations (you can swap them later)');
  console.log('  4. Write .env at the repo root');
  console.log('  5. Tell you exactly what to paste into Netlify');
  console.log('');
  console.log('Re-running this is safe — existing values are preserved.');
  console.log('');

  const existing = readExistingEnv();
  const env = { ...existing };

  // Skip the interactive flow entirely if --auto is passed.
  const auto = process.argv.includes('--auto');
  // Tier-1 #7 — opt into solo-MLRO mode at setup time. When this
  // flag is present, the wizard generates a 1-approver
  // HAWKEYE_APPROVER_KEYS pool and sets HAWKEYE_SOLO_MLRO_MODE=true
  // so the operator doesn't have to remember the env var contract.
  const soloMlro = process.argv.includes('--solo-mlro');
  const rl = auto ? null : createInterface({ input, output });

  // ─── auto-generated secrets ────────────────────────────────────────
  if (!env.HAWKEYE_BRAIN_TOKEN || env.HAWKEYE_BRAIN_TOKEN === 'REPLACE_ME_WITH_32_HEX_CHARS') {
    env.HAWKEYE_BRAIN_TOKEN = hex(24);
    console.log('✓ Generated HAWKEYE_BRAIN_TOKEN (32 hex chars)');
  }
  if (!env.AUTH_SIGNING_SECRET || env.AUTH_SIGNING_SECRET === 'your-random-32-byte-hex-secret') {
    env.AUTH_SIGNING_SECRET = hex(32);
    console.log('✓ Generated AUTH_SIGNING_SECRET (64 hex chars)');
  }
  if (!env.HAWKEYE_APPROVER_KEYS || env.HAWKEYE_APPROVER_KEYS.includes('REPLACE_ME')) {
    if (soloMlro) {
      // Solo-MLRO setup: one approver, cooldown enforces fresh-eyes.
      const k = hex(16);
      env.HAWKEYE_APPROVER_KEYS = `user-mlro:${k}`;
      env.HAWKEYE_SOLO_MLRO_MODE = 'true';
      env.HAWKEYE_SOLO_MLRO_COOLDOWN_HOURS = env.HAWKEYE_SOLO_MLRO_COOLDOWN_HOURS || '24';
      console.log('✓ Generated HAWKEYE_APPROVER_KEYS (1 solo MLRO + 24h cooldown)');
      console.log('  HAWKEYE_SOLO_MLRO_MODE=true — Cabinet Res 134/2025 Art.19 fresh-eyes');
      console.log("  enforced via 24h delay between the same MLRO's two votes.");
    } else {
      // Standard dual-MLRO setup: two distinct approvers.
      const k1 = hex(16);
      const k2 = hex(16);
      env.HAWKEYE_APPROVER_KEYS = `user-mlro-primary:${k1},user-mlro-deputy:${k2}`;
      console.log('✓ Generated HAWKEYE_APPROVER_KEYS (2 four-eyes approvers)');
      console.log('  Pass --solo-mlro to setup if you operate without a deputy.');
    }
  }
  // Normalize whatever the operator pasted so trailing slashes,
  // dots, whitespace, angle brackets, and bare hosts don't break
  // the CORS allowlist or webhook target comparison. Unset values
  // collapse to the canonical URL automatically.
  env.HAWKEYE_BRAIN_URL = normalizeBrainUrl(env.HAWKEYE_BRAIN_URL);
  if (!env.PUBLIC_BASE_URL) {
    env.PUBLIC_BASE_URL = env.HAWKEYE_BRAIN_URL;
  } else {
    env.PUBLIC_BASE_URL = normalizeBrainUrl(env.PUBLIC_BASE_URL);
  }
  if (!env.ASANA_DEFAULT_ASSIGNEE_NAME) {
    env.ASANA_DEFAULT_ASSIGNEE_NAME = 'Luisa Fernanda';
  }
  if (!env.ASANA_SCREENINGS_PROJECT_GID) {
    env.ASANA_SCREENINGS_PROJECT_GID = '1213759768596515';
  }

  // ─── interactive prompts (the only 3 things you have to type) ─────
  if (!auto && rl) {
    console.log('');
    console.log('───────────────────────────────────────────────────────────');
    console.log('  Now I need 3 things only you can give me.');
    console.log('───────────────────────────────────────────────────────────');
    console.log('');

    if (!env.ASANA_TOKEN || env.ASANA_TOKEN.startsWith('your-')) {
      console.log('1) Asana personal access token');
      console.log('   Get it here: https://app.asana.com/0/my-apps');
      console.log('   → My apps → Personal access tokens → Create new token');
      console.log('');
      const v = await ask(rl, '   ASANA_TOKEN');
      if (v) env.ASANA_TOKEN = v;
      console.log('');
    }

    if (!env.ASANA_WORKSPACE_GID) {
      console.log('2) Asana workspace GID');
      console.log('   Open any Asana page in your workspace and look at the URL:');
      console.log('     https://app.asana.com/0/<WORKSPACE_GID>/...');
      console.log('   The long number after /0/ is the workspace GID.');
      console.log('');
      const v = await ask(rl, '   ASANA_WORKSPACE_GID');
      if (v) env.ASANA_WORKSPACE_GID = v;
      console.log('');
    }

    if (!env.ASANA_AI_GOVERNANCE_PROJECT_GID) {
      console.log('3) Asana project GID for the AI Governance watchdog');
      console.log('   Create a new Asana project called "AI Governance Watchdog"');
      console.log('   Open it in the browser and copy the long number from the URL.');
      console.log('   (Press Enter to skip — the watchdog cron will be dormant.)');
      console.log('');
      const v = await ask(rl, '   ASANA_AI_GOVERNANCE_PROJECT_GID');
      if (v) env.ASANA_AI_GOVERNANCE_PROJECT_GID = v;
      console.log('');
    }

    console.log('───────────────────────────────────────────────────────────');
    console.log('  Stubbed integrations (set when credentials arrive)');
    console.log('───────────────────────────────────────────────────────────');
    console.log('');
    const stubAll = await confirm(
      rl,
      'Stub every paid integration (EOCN/goAML/banking/Reuters/Teams)?',
      true
    );
    if (stubAll) {
      for (const key of [
        'EOCN_FEED_URL',
        'GOAML_PORTAL_API_KEY',
        'BANKING_FREEZE_API_KEY',
        'REUTERS_REFINITIV_API_KEY',
        'TEAMS_WEBHOOK_URL',
      ]) {
        if (!env[key]) env[key] = 'STUB';
      }
      console.log('✓ All paid integrations stubbed (system runs in plan-only mode)');
    }
    console.log('');
  }

  if (rl) await rl.close();

  // ─── write .env ─────────────────────────────────────────────────────
  writeEnvFile(env);
  console.log('');
  console.log(`✓ Wrote ${ENV_PATH}`);
  console.log('');

  // ─── next-steps printout ────────────────────────────────────────────
  console.log('═══════════════════════════════════════════════════════════');
  console.log('  ALL DONE LOCALLY. Next: provision Asana + push to Netlify.');
  console.log('═══════════════════════════════════════════════════════════');
  console.log('');
  console.log('STEP 1 — Provision the Asana workspace (custom fields,');
  console.log('         sections, webhook subscriptions). Run from this');
  console.log('         repo with the local .env loaded:');
  console.log('');
  console.log('   set -a; source .env; set +a   # load .env into your shell');
  console.log('   npm run asana:bootstrap -- --apply');
  console.log('');
  console.log('   Paste the printed export ASANA_CF_* lines back into .env.');
  console.log('');
  console.log('STEP 2 — Provision the inspector evidence project (Tier-4 #14):');
  console.log('');
  console.log('   npm run asana:bootstrap:inspector -- --apply');
  console.log('');
  console.log('   Then in Asana: open the new project → Share → add inspector');
  console.log('   by email → set permission to "View only".');
  console.log('   Paste the printed export ASANA_INSPECTOR_PROJECT_GID into .env.');
  console.log('');
  console.log('STEP 3 — Manually create 2 cross-project mirror destinations');
  console.log('         in the Asana UI (no script — these are operator-named):');
  console.log('');
  console.log('   • 🚨 MLRO Central — Blocked Across Customers');
  console.log('       → paste GID into ASANA_CENTRAL_MLRO_PROJECT_GID');
  console.log('   • 📜 Compliance Audit Log — 10-Year Retention');
  console.log('       → paste GID into ASANA_AUDIT_LOG_PROJECT_GID');
  console.log('');
  console.log('STEP 4 — Validate the env file before pushing:');
  console.log('');
  console.log('   set -a; source .env; set +a');
  console.log('   npm run asana:env:check');
  console.log('');
  console.log('   Resolve any 🚫 BLOCKER lines. Warnings are acceptable but');
  console.log('   indicate features that will silently no-op until configured.');
  console.log('');
  console.log('STEP 5 — Push to Netlify.');
  console.log('');
  console.log('Option A — one-line CLI push (easiest):');
  console.log('');
  console.log('   npx netlify-cli login           # browser opens, click "Authorize"');
  console.log('   npx netlify-cli link            # pick your site from the list');
  console.log('   npx netlify-cli env:import .env # pushes every var in .env');
  console.log('');
  console.log('Option B — Netlify dashboard:');
  console.log('');
  console.log('   1. Open https://app.netlify.com');
  console.log('   2. Pick the hawkeye-sterling-v2 site');
  console.log('   3. Site settings → Environment variables');
  console.log('   4. Paste each KEY=VALUE from .env');
  console.log('   5. Click "Trigger redeploy"');
  console.log('');
  console.log('STEP 6 — Smoke-test the autopilot after the redeploy:');
  console.log('');
  console.log(
    '   curl https://hawkeye-sterling-v2.netlify.app/.netlify/functions/asana-super-brain-autopilot-cron'
  );
  console.log('');
  console.log('Expected: {"ok":true,"dispatched":N,...}');
  console.log('');
  if (env.HAWKEYE_SOLO_MLRO_MODE === 'true') {
    console.log('NOTE — Solo MLRO mode is ON. Freeze + escalate decisions');
    console.log('       require two votes from you, with a 24h cooldown between');
    console.log('       them enforced server-side. Cast vote 1 in the analyzer');
    console.log('       UI, sleep on it, cast vote 2 the next day.');
    console.log('');
  }
  console.log('That is it. From .env to a live autopilot with all 3 mirrors,');
  console.log('the central MLRO triage queue, the audit-log retention copy,');
  console.log('and the inspector evidence project — wired end-to-end.');
  console.log('');
}

main().catch((err) => {
  console.error('');
  console.error('Setup failed:', err.message);
  console.error('');
  process.exit(1);
});
