/**
 * Red Flag Library — UAE AML/CFT/CPF Compliance for DPMS Sector
 *
 * Sources:
 *   - FDL No.10/2025 (UAE AML/CFT Law)
 *   - Cabinet Resolution 134/2025 (Implementing Regulations)
 *   - Cabinet Resolution 156/2025 (PF & Dual-Use Controls)
 *   - FATF 40 Recommendations & DPMS Sector Guidance
 *   - UAE National Risk Assessment 2024
 *   - MoE Circular 08/AML/2021 & MoE Sector Guidance for DPMS
 *   - FIU goAML Reporting Guidelines
 *   - EOCN Asset Freeze & TFS Protocols
 *   - LBMA Responsible Gold Guidance v9
 *   - Egmont Group Typologies for Precious Metals
 */

export type RedFlagCategory =
  | "customer"
  | "transaction"
  | "sanctions"
  | "pf"
  | "sourcing"
  | "sof-sow"
  | "kyc"
  | "pep"
  | "geographic"
  | "documentation"
  | "behavioral"
  | "precious-metals";

export interface RedFlagDefinition {
  code: string;
  title: string;
  description: string;
  category: RedFlagCategory;
  likelihood: 1 | 2 | 3 | 4 | 5;
  impact: 1 | 2 | 3 | 4 | 5;
  autoTriggersEDD: boolean;
  autoTriggersSTRReview: boolean;
  autoBlocksProcessing: boolean;
  regulatoryRef: string;
}

export const RED_FLAGS: RedFlagDefinition[] = [
  // ─── Transaction Red Flags (RF001–RF015) ─────────────────────────────────
  {
    code: "RF001",
    title: "Unjustified increase in precious metals supply",
    description: "Prominent increase in supply or purchase without supporting business rationale",
    category: "transaction",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.15, UAE NRA 2024, MoE DPMS Guidance",
  },
  {
    code: "RF002",
    title: "Structuring / smurfing below AED 55,000 threshold",
    description: "Multiple transactions structured just below the DPMS reporting threshold",
    category: "transaction",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.16, FATF Rec 22, MoE Circular 08/AML/2021",
  },
  {
    code: "RF003",
    title: "Rapid buy-sell cycle",
    description: "Purchase and return/resale of precious metals within an unusually short period",
    category: "transaction",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "UAE NRA 2024 DPMS Typologies, Egmont Group PM Indicators",
  },
  {
    code: "RF004",
    title: "Round-tripping / circular payments",
    description: "Circular payment patterns suggesting layering through precious metals transactions",
    category: "transaction",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025, FATF Typologies for DPMS",
  },
  {
    code: "RF005",
    title: "Cash transaction at or above AED 55,000",
    description: "Single cash transaction at or exceeding the DPMS cash threshold requiring CTR filing",
    category: "transaction",
    likelihood: 5,
    impact: 4,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.16, MoE Circular 08/AML/2021, FATF Rec 22",
  },
  {
    code: "RF006",
    title: "Transaction-profile mismatch",
    description: "Transaction amount or frequency inconsistent with customer's declared business profile",
    category: "transaction",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Res 134/2025 Art.16, UAE NRA 2024",
  },
  {
    code: "RF007",
    title: "Third-party payer / beneficiary",
    description: "Payment made by or on behalf of a party other than the identified customer",
    category: "transaction",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Res 134/2025 Art.6(3), FATF Rec 10/22",
  },
  {
    code: "RF008",
    title: "Unusual settlement method",
    description: "Use of virtual assets, prepaid cards, e-wallets, hawala, or informal value transfer",
    category: "transaction",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.17, FATF Rec 15 (Virtual Assets)",
  },
  {
    code: "RF009",
    title: "Back-to-back transactions",
    description: "Near-simultaneous buy and sell of same commodity suggesting trade-based laundering",
    category: "transaction",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FATF Trade-Based ML Typologies, UAE NRA 2024",
  },
  {
    code: "RF010",
    title: "Transaction after prolonged dormancy",
    description: "Significant transaction following extended period of account inactivity",
    category: "transaction",
    likelihood: 3,
    impact: 3,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.15, MoE DPMS Guidance",
  },

  // ─── Sanctions Red Flags (RF011–RF015) ───────────────────────────────────
  {
    code: "RF011",
    title: "Sanctions list match",
    description: "Customer, UBO, or counterparty appears on UN/OFAC/EU/UAE sanctions lists",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.22-23, Cabinet Res 156/2025, EOCN Protocol, UNSC Resolutions",
  },
  {
    code: "RF012",
    title: "Sanctions evasion indicators",
    description: "Patterns suggesting deliberate circumvention of targeted financial sanctions",
    category: "sanctions",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.22, FATF Rec 6, EOCN TFS Guidance",
  },
  {
    code: "RF013",
    title: "Designated entity proximity",
    description: "Customer has business relationships or shared addresses with designated entities",
    category: "sanctions",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FATF Rec 6/7, Cabinet Res 156/2025, UAE TFS Framework",
  },

  // ─── PEP Red Flags (RF016–RF019) ────────────────────────────────────────
  {
    code: "RF016",
    title: "PEP identified — customer or UBO",
    description: "Customer or beneficial owner identified as Politically Exposed Person",
    category: "pep",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.18, FATF Rec 12, Cabinet Res 134/2025 Art.8",
  },
  {
    code: "RF017",
    title: "PEP family member or close associate",
    description: "Customer is a family member or close associate of a PEP",
    category: "pep",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.18, FATF Rec 12/22",
  },
  {
    code: "RF018",
    title: "Complex ownership structure",
    description: "Ownership structure is unnecessarily complex, obscuring beneficial ownership",
    category: "customer",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.14, FATF Rec 10/24, MoE UBO Guidance",
  },
  {
    code: "RF019",
    title: "PEP with unexplained wealth",
    description: "PEP customer with wealth or source of funds inconsistent with known legitimate income",
    category: "pep",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.18, FATF Rec 12, MoE DPMS Guidance",
  },

  // ─── Geographic / Jurisdiction Red Flags (RF020–RF025) ───────────────────
  {
    code: "RF020",
    title: "FATF grey/black list jurisdiction",
    description: "Transaction involves jurisdiction on FATF list of high-risk or monitored countries",
    category: "geographic",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.17, FATF Rec 19, MoE Circular",
  },
  {
    code: "RF021",
    title: "Conflict-affected or high-risk area (CAHRA)",
    description: "Gold or precious metals originating from or transiting through a CAHRA",
    category: "geographic",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "LBMA RGG v9, OECD Due Diligence Guidance, UAE NRA 2024",
  },
  {
    code: "RF022",
    title: "Free zone / offshore routing",
    description: "Transaction routed through free trade zones or offshore centers without clear rationale",
    category: "geographic",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.17, FATF Rec 19, UAE NRA 2024",
  },
  {
    code: "RF023",
    title: "Multi-jurisdiction transshipment",
    description: "Goods transshipped through multiple jurisdictions without apparent commercial reason",
    category: "geographic",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FATF Rec 7, OFAC Advisories, Cabinet Res 156/2025",
  },
  {
    code: "RF024",
    title: "Complex payment methods",
    description: "Virtual assets, prepaid cards, e-wallets, PayPal, or cryptocurrency payments",
    category: "transaction",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025, FATF Rec 15, MoE Virtual Asset Guidance",
  },
  {
    code: "RF025",
    title: "High-risk country for PF",
    description: "Transaction involves DPRK, Iran, or Syria — designated PF high-risk jurisdictions",
    category: "pf",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "Cabinet Res 156/2025, FATF Rec 7, UNSC Res 1718/2231, EOCN Protocol",
  },

  // ─── KYC / Documentation Red Flags (RF030–RF039) ────────────────────────
  {
    code: "RF030",
    title: "Incomplete or outdated KYC documentation",
    description: "Customer KYC file missing required documents or documents past expiry date",
    category: "kyc",
    likelihood: 3,
    impact: 3,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.12-13, Cabinet Res 134/2025 Art.4-6, MoE KYC Standards",
  },
  {
    code: "RF031",
    title: "Conflicting customer information",
    description: "Inconsistencies between customer-provided documents or between documents and declarations",
    category: "kyc",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Res 134/2025 Art.6, FATF Rec 10",
  },
  {
    code: "RF032",
    title: "Refusal to provide required information",
    description: "Customer refuses or is unable to provide standard KYC/CDD documentation",
    category: "behavioral",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.12, Cabinet Res 134/2025 Art.4, FATF Rec 10",
  },
  {
    code: "RF033",
    title: "Suspected forged or falsified documents",
    description: "Documents appear altered, fraudulent, or inconsistent with official records",
    category: "documentation",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.26, MoE Document Verification Standards",
  },
  {
    code: "RF034",
    title: "Unverifiable beneficial ownership",
    description: "Unable to identify or verify the ultimate beneficial owner(s) of the entity",
    category: "kyc",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.14, FATF Rec 10/24, Cabinet Res 134/2025 Art.7",
  },
  {
    code: "RF035",
    title: "Nominee / shell company indicators",
    description: "Entity appears to be a shell company or nominee arrangement with no genuine business",
    category: "customer",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FATF Rec 24/25, UAE NRA 2024, MoE UBO Guidance",
  },

  // ─── Source of Funds / Wealth Red Flags (RF040–RF049) ────────────────────
  {
    code: "RF040",
    title: "No apparent business rationale",
    description: "Transaction has no discernible economic or business purpose",
    category: "sof-sow",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.15, FATF Rec 10/20, MoE DPMS Guidance",
  },
  {
    code: "RF041",
    title: "False certificates of origin",
    description: "Origin certificates appear false, manipulated, or inconsistent with shipment data",
    category: "sourcing",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "LBMA RGG v9, OECD DDG, UAE Customs Regulations, MoE DPMS Guidance",
  },
  {
    code: "RF042",
    title: "Cash deposits followed by wire transfers",
    description: "Pattern of cash deposits immediately followed by outbound wire transfers",
    category: "sof-sow",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.15-16, FATF Typologies, Egmont Group Indicators",
  },
  {
    code: "RF043",
    title: "Unexplained wealth relative to profile",
    description: "Customer's financial activity inconsistent with known occupation or business size",
    category: "sof-sow",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.14-15, FATF Rec 10, MoE SOF/SOW Guidance",
  },

  // ─── Precious Metals Specific Red Flags (RF050–RF059) ────────────────────
  {
    code: "RF050",
    title: "Precious metals valuation anomaly",
    description: "Declared value deviates more than 25% from market benchmark price",
    category: "precious-metals",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "UAE NRA 2024, FATF Rec 20, MoE DPMS Sector Guidance",
  },
  {
    code: "RF051",
    title: "Weight / purity discrepancy",
    description: "Declared weight or purity inconsistent with assay results or industry norms",
    category: "precious-metals",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "LBMA Good Delivery Rules, MoE DPMS Guidance",
  },
  {
    code: "RF052",
    title: "Unusual commodity mix",
    description: "Mixed shipment of gold, diamonds, and rare metals without clear commercial logic",
    category: "precious-metals",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "UAE NRA 2024 DPMS Typologies, LBMA RGG v9",
  },
  {
    code: "RF053",
    title: "Missing hallmark or assay certification",
    description: "Precious metals lack required hallmarking, assay reports, or quality certification",
    category: "precious-metals",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "MoE DPMS Regulations, UAE Standards (ESMA), LBMA GDR",
  },
  {
    code: "RF054",
    title: "Artisanal / small-scale mining indicators",
    description: "Gold sourced from artisanal mining regions without proper chain-of-custody documentation",
    category: "sourcing",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "LBMA RGG v9, OECD DDG Annex II, UAE NRA 2024",
  },

  // ─── Behavioral Red Flags (RF060–RF065) ──────────────────────────────────
  {
    code: "RF060",
    title: "Customer attempts to avoid reporting",
    description: "Customer explicitly requests transactions below thresholds or asks about reporting limits",
    category: "behavioral",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.16/26, MoE Circular 08/AML/2021",
  },
  {
    code: "RF061",
    title: "Unusual urgency or pressure",
    description: "Customer insists on immediate completion, cash settlement, or bypassing normal procedures",
    category: "behavioral",
    likelihood: 4,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FATF DPMS Guidance, UAE NRA 2024",
  },
  {
    code: "RF062",
    title: "Adverse media findings",
    description: "Negative media coverage linking customer to financial crime, corruption, or sanctions evasion",
    category: "customer",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.14, FATF Rec 10, MoE EDD Requirements",
  },
  {
    code: "RF063",
    title: "Sudden change in transaction patterns",
    description: "Abrupt shift in volume, frequency, or counterparties without business explanation",
    category: "behavioral",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.15, UAE NRA 2024",
  },

  // ─── SOF / SOW Red Flags (RF067–RF069) ───────────────────────────────────
  {
    code: "RF067",
    title: "Unverified source of funds",
    description: "Source of funds is unverified, unexplained, or inconsistent with declared activities",
    category: "sof-sow",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "FDL No.10/2025 Art.14-15, FATF Rec 10, Cabinet Res 134/2025 Art.6, MoE SOF Guidance",
  },
  {
    code: "RF068",
    title: "Unverified source of wealth",
    description: "Customer's overall wealth cannot be reasonably verified or explained",
    category: "sof-sow",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.14, FATF Rec 10, MoE SOW Guidance",
  },

  // ─── Proliferation Financing Red Flags (RF070–RF075) ─────────────────────
  {
    code: "RF070",
    title: "Strategic goods list match",
    description: "Goods appear on UAE Strategic Goods and Dual-Use Control Lists",
    category: "pf",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "Cabinet Res 156/2025 Art.3-5, UNSC Res 1718/2231, EOCN Protocol",
  },
  {
    code: "RF071",
    title: "Dual-use material indicators",
    description: "Goods description contains dual-use indicators (industrial platinum, centrifuge components, etc.)",
    category: "pf",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Res 156/2025, FATF Rec 7, UNSC Resolutions",
  },
  {
    code: "RF072",
    title: "Missing end-use declaration for high-risk destination",
    description: "No or insufficient end-use declaration for goods destined to PF high-risk jurisdiction",
    category: "pf",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "Cabinet Res 156/2025, FATF Rec 7, UNSC Resolutions",
  },
  {
    code: "RF073",
    title: "Industrial-grade precious metals in unusual quantity",
    description: "Industrial-grade precious metals ordered in quantities inconsistent with declared business",
    category: "pf",
    likelihood: 3,
    impact: 4,
    autoTriggersEDD: true,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Res 156/2025 Art.7, FATF Rec 1/7",
  },
  // ─── EOCN / TFS Compliance Red Flags (RF074–RF081) ──────────────────────
  {
    code: "RF074",
    title: "Delayed TFS screening after EOCN designation",
    description: "Screening not conducted within 24 hours of new EOCN/UNSC designation notification",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN TFS Guidance, Cabinet Resolution 74/2020 Art.4, FDL No.10/2025 Art.14",
  },
  {
    code: "RF075",
    title: "CNMR not filed within 5 business days",
    description: "Compliance No-Match Report not filed with EOCN within required timeframe after confirmed or partial match",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN TFS Guidance, Cabinet Resolution 74/2020 Art.6",
  },
  {
    code: "RF076",
    title: "TFS freeze not executed without delay",
    description: "Assets not frozen immediately upon confirmed match against EOCN/UNSC lists",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN TFS Guidance, Cabinet Resolution 74/2020 Art.4-5, FATF Rec.6",
  },
  {
    code: "RF077",
    title: "TFS evasion through nominees or agents",
    description: "Attempt to circumvent TFS measures using agents, nominees, or alternative payment channels",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN TFS Guidance, Cabinet Resolution 74/2020 Art.5, FDL No.10/2025 Art.14",
  },
  {
    code: "RF078",
    title: "Unauthorized de-listing or unfreezing",
    description: "De-listing or unfreezing of assets executed without prior EOCN authorization",
    category: "sanctions",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN TFS Guidance, Cabinet Resolution 74/2020 Art.7",
  },
  // ─── PF Institutional Risk Assessment Red Flags (RF079–RF088) ───────────
  {
    code: "RF079",
    title: "PF institutional risk assessment not conducted",
    description: "Entity has not conducted or updated PF risk assessment within 12 months as required by EOCN guidance",
    category: "pf",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "EOCN PF RA Guidance 2025, Cabinet Resolution 134/2025 Art.5, FDL No.10/2025 Art.6",
  },
  {
    code: "RF080",
    title: "State-sponsored procurement network nexus",
    description: "Customer or counterparty linked to state-sponsored procurement networks of PF-sanctioned countries",
    category: "pf",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN PF Guidance 2025, UNSCR 1718/2231, Cabinet Resolution 74/2020",
  },
  {
    code: "RF081",
    title: "Transhipment to obscure PF destination",
    description: "Shipping routed through free zones or multiple intermediaries to obscure final delivery to PF-sanctioned entity",
    category: "pf",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN PF Guidance 2025, Cabinet Resolution 156/2025, FATF Rec.7",
  },
  {
    code: "RF082",
    title: "Academic or diplomatic cover for dual-use procurement",
    description: "Customer uses academic, research, or diplomatic cover to procure controlled or dual-use materials",
    category: "pf",
    likelihood: 4,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN PF Guidance 2025, UNSCR 1540, FATF PF Guidance 2021",
  },
  {
    code: "RF083",
    title: "Military or defence entity of PF-sanctioned country",
    description: "Customer linked to military, intelligence, or defence procurement entity of DPRK, Iran, or Syria",
    category: "pf",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: true,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: true,
    regulatoryRef: "EOCN PF Guidance 2025, UNSCR 1718/2231, FATF Rec.7",
  },
  // ─── UAE FIU / goAML Reporting Red Flags (RF084–RF088) ──────────────────
  {
    code: "RF084",
    title: "STR not filed within prescribed timeline",
    description: "Failure to file STR/SAR with FIU via goAML after identifying suspicious activity within required deadline",
    category: "transaction",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.26-27, UAE FIU Guidance, FATF Rec.20",
  },
  {
    code: "RF085",
    title: "DPMSR not filed for cash threshold breach",
    description: "DPMS Report not filed for single or cumulative cash transactions at or above AED 55,000",
    category: "transaction",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: true,
    autoBlocksProcessing: false,
    regulatoryRef: "MoE Circular 08/AML/2021, FDL No.10/2025 Art.16, FATF Rec.22",
  },
  {
    code: "RF086",
    title: "No compliance manual or EWRA during MOE inspection",
    description: "Entity unable to produce compliance manual, EWRA/BWRA, or risk appetite statement during MOE inspection",
    category: "documentation",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "Cabinet Resolution 134/2025 Art.5-6, FDL No.10/2025 Art.20-21, MoE Inspection Framework",
  },
  {
    code: "RF087",
    title: "CO/MLRO not appointed or unqualified",
    description: "Compliance Officer or MLRO not appointed or does not meet minimum competency requirements set by MoE",
    category: "documentation",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.20, Cabinet Resolution 134/2025 Art.18, MoE DPMS Guidance",
  },
  {
    code: "RF088",
    title: "Records destroyed before 5-year retention period",
    description: "Customer or transaction records destroyed before the mandatory 5-year retention period expires",
    category: "documentation",
    likelihood: 5,
    impact: 5,
    autoTriggersEDD: false,
    autoTriggersSTRReview: false,
    autoBlocksProcessing: false,
    regulatoryRef: "FDL No.10/2025 Art.24, Cabinet Resolution 134/2025 Art.21, MoE Inspection Framework",
  },
];
